fix

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -48,6 +48,11 @@ jobs:
     - name: Install cert-manager
       run: |
         kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.yaml
+        for i in {1..20}; do
+            output=$(kubectl get pods --no-headers -o wide -n cert-manager | grep -vw Completed || echo 'Fail')
+            grep -vE '([0-9]+)/\1 +Running' <<< $output || break
+            [ $i -ne 20 ] && sleep 30 || { echo "Godot: pods not running"; exit 1; }
+        done
     - name: Install package
       run: |
         sudo apt-get -y install jq
